#!/usr/bin/env node
'use strict';
let fs         = require('fs');
let browserify = require('browserify');
let babelify   = require('babelify');

let debug = process.argv[2] === "--debug";
let target = `dist/onion-sticky.browserify-shim${ debug ? '.debug' : '' }.js`;

browserify({ debug })
  .transform(babelify)
  .require(require.resolve('../onion-sticky.js'), { entry: true })
  .on("error", function (err) { console.log("Error : " + err.message); })
  .bundle()
  .pipe(fs.createWriteStream(target))
;
